name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  check-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: check-test
    steps:
      - name: Use Node.js 21.x
        uses: actions/setup-node@v2
        with:
          node-version: 21.x
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install netlify-cli -g
      
      - name: Install dependencies
        run: npm install
      - name: Install netlify cli
        run: npm i netlify-cli deploy

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} 
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify-cli deploy --prod --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --dir dist
